"""Centralised ErrorCode enum for all ai_editor subsystems.

Every typed error across Session, Buffer, File, Formatter, Address, Search,
Clipboard, YAML, CST, Validation, Mutation, Write, and History subsystems
is defined here. No subsystem may define its own ad-hoc error strings.
"""
from __future__ import annotations

from enum import Enum


class ErrorCode(str, Enum):
    """Typed error codes for all ai_editor operations."""

    # --- Session ---
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    SESSION_REGISTRATION_FAILED = "SESSION_REGISTRATION_FAILED"
    SESSION_LOCK_CONFLICT = "SESSION_LOCK_CONFLICT"
    SESSION_HAS_UNSAVED_BUFFERS = "SESSION_HAS_UNSAVED_BUFFERS"
    SESSION_READONLY = "SESSION_READONLY"
    SESSION_HAS_UNSENT_FILES = "SESSION_HAS_UNSENT_FILES"

    # --- Buffer ---
    BUFFER_NOT_FOUND = "BUFFER_NOT_FOUND"
    BUFFER_ALREADY_OPEN = "BUFFER_ALREADY_OPEN"
    BUFFER_HAS_UNSAVED_CHANGES = "BUFFER_HAS_UNSAVED_CHANGES"
    BUFFER_STALE = "BUFFER_STALE"
    BUFFER_INVALID = "BUFFER_INVALID"
    BUFFER_LOCKED = "BUFFER_LOCKED"
    BUFFER_READONLY = "BUFFER_READONLY"

    # --- File ---
    FILE_HAS_UNSENT_CHANGES = "FILE_HAS_UNSENT_CHANGES"

    # --- Formatter ---
    FORMATTER_NOT_FOUND = "FORMATTER_NOT_FOUND"
    FORMATTER_UNSUPPORTED = "FORMATTER_UNSUPPORTED"
    FORMATTER_COMMAND_DISCOVERY_FAILED = "FORMATTER_COMMAND_DISCOVERY_FAILED"
    FORMATTER_COMMAND_SCHEMA_INVALID = "FORMATTER_COMMAND_SCHEMA_INVALID"
    FORMATTER_COMMAND_UNSUPPORTED = "FORMATTER_COMMAND_UNSUPPORTED"
    FORMAT_VALIDATION_FAILED = "FORMAT_VALIDATION_FAILED"
    FORMAT_INVALID_ON_OPEN = "FORMAT_INVALID_ON_OPEN"

    # --- Address / path ---
    PATH_PARSE_FAILED = "PATH_PARSE_FAILED"
    PATH_NOT_FOUND = "PATH_NOT_FOUND"
    PATH_NOT_UNIQUE = "PATH_NOT_UNIQUE"
    TARGET_TYPE_MISMATCH = "TARGET_TYPE_MISMATCH"
    ADDRESS_INVALID = "ADDRESS_INVALID"
    ADDRESS_NOT_FOUND = "ADDRESS_NOT_FOUND"
    ADDRESS_NOT_UNIQUE = "ADDRESS_NOT_UNIQUE"

    # --- Search ---
    SEARCH_QUERY_INVALID = "SEARCH_QUERY_INVALID"
    SEARCH_NO_MATCH = "SEARCH_NO_MATCH"
    SEARCH_NOT_UNIQUE = "SEARCH_NOT_UNIQUE"
    SEARCH_SCOPE_INVALID = "SEARCH_SCOPE_INVALID"
    FORMATTER_SEARCH_UNSUPPORTED = "FORMATTER_SEARCH_UNSUPPORTED"

    # --- Clipboard ---
    CLIPBOARD_EMPTY = "CLIPBOARD_EMPTY"
    CLIPBOARD_ITEM_NOT_FOUND = "CLIPBOARD_ITEM_NOT_FOUND"
    CLIPBOARD_FORMAT_MISMATCH = "CLIPBOARD_FORMAT_MISMATCH"
    CLIPBOARD_SOURCE_STALE = "CLIPBOARD_SOURCE_STALE"
    CLIPBOARD_INVALID_MODE = "CLIPBOARD_INVALID_MODE"

    # --- YAML ---
    YAML_PARSE_FAILED = "YAML_PARSE_FAILED"
    SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED"
    SEMANTIC_VALIDATION_FAILED = "SEMANTIC_VALIDATION_FAILED"
    RENDER_NOT_DETERMINISTIC = "RENDER_NOT_DETERMINISTIC"
    CHANGED_PATH_MISMATCH = "CHANGED_PATH_MISMATCH"

    # --- CST ---
    CST_PARSE_FAILED = "CST_PARSE_FAILED"

    # --- Validation ---
    VALIDATION_FAILED = "VALIDATION_FAILED"

    # --- Mutation ---
    MUTATION_ROLLBACK = "MUTATION_ROLLBACK"
    PRE_WRITE_VALIDATION_FAILED = "PRE_WRITE_VALIDATION_FAILED"

    # --- Write ---
    WRITE_FAILED = "WRITE_FAILED"
    BACKUP_FAILED = "BACKUP_FAILED"
    SAVE_TARGET_EXISTS = "SAVE_TARGET_EXISTS"
    SAVE_TARGET_MISSING = "SAVE_TARGET_MISSING"

    # --- History ---
    UNDO_AT_BEGINNING = "UNDO_AT_BEGINNING"
    REDO_AT_END = "REDO_AT_END"
    HISTORY_UNAVAILABLE = "HISTORY_UNAVAILABLE"
    GIT_COMMIT_FAILED = "GIT_COMMIT_FAILED"
    GIT_NOT_AVAILABLE = "GIT_NOT_AVAILABLE"
